---

 - name: remove old idea repository
   become: yes
   apt_repository: repo="ppa:mmk2410/intellij-idea-community" state="absent"

 - name: add idea repository
   become: yes
   apt_repository: repo="ppa:mmk2410/intellij-idea"
