---

 - name: install nvm manager for current user
   shell: wget -qO- https://raw.githubusercontent.com/creationix/nvm/{{nvm_version}}/install.sh | bash

 - name: install node LTS
   shell: "source ~/.nvm/nvm.sh && nvm install --lts"
   args:
     executable: /bin/bash
   register: nvm_install_result
   changed_when: "'is already installed.' not in nvm_install_result.stdout and 'is already installed.' not in nvm_install_result.stderr"
