---

   - name: install chromium because this browser is best choice when it comes to debugging of javascript code
     become: yes
     apt:
       name:
         - chromium-browser
         - chromium-browser-l10n
       state: latest
