---

 - name: get nodjs box, prevent package poisoning of development host machine
   git: repo="https://github.com/andreasbehnke/nodejs-vagrantbox.git" dest="{{src_nodejs_vagrantbox}}"
   register: nodejs_vagrantbox_repo

 - name: environment configuration
   template: src=environment.rb.j2 dest={{src_nodejs_vagrantbox}}/environment.rb

 - name: drop box if repository changed
   when: nodejs_vagrantbox_repo.changed
   command: vagrant destroy -f chdir="{{src_nodejs_vagrantbox}}"

 - name: test status of vagrant environment
   command: vagrant status chdir="{{src_nodejs_vagrantbox}}"
   register: nodejs_vagrantbox_status
   changed_when: False

 - name: provisioning vagrant box
   when: nodejs_vagrantbox_status.stdout.find('not created') != -1
   command: vagrant up chdir="{{src_nodejs_vagrantbox}}"

 - name: stop vagrant box
   when: nodejs_vagrantbox_status.stdout.find('not created') != -1
   command: vagrant halt chdir="{{src_nodejs_vagrantbox}}"
