---

- hosts: all

  pre_tasks:
   - name: update apt cache
     become: yes
     apt: update_cache=yes
     changed_when: False

  roles:
   - scm
   #- source-code-editor
   #- database-development
   #- java-development
   #- java-development-ide
   #- virtualization
   #- source-environment
   #- javascript-development
   #- ansible-development
   #- image-manipulation
