---

- hosts: all

  pre_tasks:
   - name: update apt cache
     become: yes
     apt: update_cache=yes
     changed_when: False

  roles:
   - scm
   - source-code-editor
   - python-development
   - ansible-development
   - virtualization
   - aws-tools
   - database-development
   - java-development
  # - java-development-ide
   - javascript-development
   - image-manipulation
   - source-environment
   - rest-api-development
