---

 - name: install dependencies
   become: yes
   apt: name=software-properties-common state=latest

 - name: install ansible repository
   become: yes
   apt_repository: repo="ppa:ansible/ansible"

 - name: install ansible
   become: yes
   apt: name=ansible state=latest
