---

 - name: install openjdk and build tools
   become: yes
   tags: java
   apt:
     name:
       - openjdk-8-source
       - openjdk-8-jdk
       - openjdk-8-jre
       - maven
     state: latest
   
 - name: set JAVA_HOME
   become: yes
   tags: java
   lineinfile: dest=/etc/environment state=present regexp='^JAVA_HOME' line='JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64'
   register: set_java_home
