---

 - name: install python pip
   become: yes
   apt:
     name:
       - python-dev
       - python-pip
       - python3-dev
       - python3-pip
     state: latest
   tags: python

 - name: install pipenv
   become: yes
   pip:
     name: pipenv
