---
 - name: install postgres client tools
   become: yes
   apt:
     name:
       - postgresql-client
       - pgadmin3
     state: latest

 - name: install dbeaver
   become: yes
   apt: deb={{ dbeaver_url_deb }}
