---

 - name: install postgres client tools
   become: yes
   apt: name={{ item }} state=latest
   with_items:
     - postgresql-client
     - pgadmin3

 - name: install dbeaver
   become: yes
   apt: deb={{ dbeaver_url_deb }}  
