---

 - name: install git and diff viewer
   become: yes
   apt: name={{ item }} state=latest
   with_items:
     - git
     - git-crypt # supports partial repository encryption
     - meld   # used as diff viewer
     - mr     # manage multiple repositories

# configure git
 - name: git configuration
   template: src=gitconfig.j2 dest="{{ ansible_env.HOME}}/.gitconfig"
   when: user_email is defined

# add scm information to bash prompt

 - name: ensure bash configuration folder
   file: path={{ ansible_env.HOME}}/.bash state=directory

 - name: retrieve repo git-aware-prompt
   git: repo="https://github.com/andreasbehnke/git-aware-prompt.git" dest="{{ ansible_env.HOME}}/.bash/git-aware-prompt"

 - name: configure git aware prompt
   blockinfile: |
     dest='{{ ansible_env.HOME}}/.bashrc'
     content="export PROMPT_DIRTRIM=2
        export GITAWAREPROMPT=~/.bash/git-aware-prompt
        source \"${GITAWAREPROMPT}/main.sh\"
        export PS1=\"\[\033[01;34m\]\w\[\033[00m\] \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]\$ \""
