---

 - name: install git and diff viewer
   become: yes
   apt: name={{ item }} state=latest
   with_items:
     - git
     - meld   # used as diff viewer
     - mr     # manage multiple repositories
