---

 - name: add key for docker repository
   become: yes
   apt_key: url="https://download.docker.com/linux/ubuntu/gpg" state=present

 - name: add docker repository
   become: yes
   apt_repository: repo='deb https://download.docker.com/linux/ubuntu yakkety stable' state=present filename='docker' update_cache='yes'

 - name: install docker
   become: yes
   apt: name=docker-ce state=latest force=yes
