---

 - name: add key for docker repository
   become: yes
   apt_key: url="https://download.docker.com/linux/ubuntu/gpg" state=present

 - name: add docker repository
   become: yes
   apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} edge" state="present" filename="docker" update_cache="yes"

 - name: install docker
   become: yes
   apt: name=docker-ce state=latest force=yes

 - name: do not start docker at boot time (consumes a lot of notebook power), start docker only on demand
   become: yes
   systemd: name=docker.service daemon-reload=yes enabled=no

 - name: adding existing user to group docker
   become: yes
   user: name='{{ ansible_env.USER }}' groups='docker' state=present append=yes
   
 - name: install docker-compose
   become: yes
   get_url: url="{{docker_compose_url}}" dest="/usr/local/bin/docker-compose" mode="u=rwx,g=rx,o=rx"
