---

 - name: install virtualbox and vagrant
   become: yes
   apt: name={{ item }} state=latest
   with_items:
    - virtualbox
    - vagrant
    - ruby-dev # required by vagrant-hosts
    - htop     # nice to see memory usage

 - name: install vagrant plugins - gem
   become: yes
   gem: name={{item}} user_install=no state=latest
   with_items: "{{vagrant_plugins}}"

 - name: install vagrant plugins - vagrant
   command: vagrant plugin install {{item}}
   with_items: "{{vagrant_plugins}}"
   changed_when: false
