---

 - name: install virtualbox and vagrant
   become: yes
   apt: name={{ item }} state=latest
   with_items:
    - virtualbox
    - vagrant
    - htop # nice to see memory usage

 - name: install vagrant plugin vbguest
   become: yes
   gem: name=vagrant-vbguest user_install=no state=latest
