---

 - name: install vagrant dependencies
   become: yes
   apt:
     name:
       - ruby-dev       # required by vagrant-hosts
       - htop           # nice to see memory usage
     state: latest
     
 - name: install vagrant using debian package from hashicorp
   become: yes
   apt: deb={{vagrant_url_deb}}

 - name: install vagrant plugins - vagrant
   command: vagrant plugin install {{item}}
   with_items: "{{vagrant_plugins}}"
   changed_when: false
