---

# copied from this repository: https://github.com/azavea/ansible-virtualbox

 - name: configure the Oracle APT key
   become: yes
   apt_key: url=https://www.virtualbox.org/download/oracle_vbox_2016.asc state=present

 - name: configure the VirtualBox APT repositories
   become: yes
   apt_repository: repo="deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib" state=present filename='virtualbox' update_cache='yes'

 - name: install VirtualBox
   become: yes
   apt: name=virtualbox-{{ virtualbox_version }} state=present
