---

 - name: ensure personal source base folder
   file: path="{{ src_base }}" state=directory
   when: src_base is defined

 - name: checkout working repositories
   git: repo="{{ item.url }}" dest="{{ src_base }}/{{ item.name }}" accept_hostkey=yes update=no
   with_items: "{{ dev_repositories }}"
   when: dev_repositories is defined

 - name: configure mr
   template: src=mrconfig.j2 dest="{{ ansible_env.HOME}}/.mrconfig"
   when: dev_repositories is defined
